"""course_material_change

Revision ID: 0d2b9fe59d5a
Revises: ce3b5d19e70a
Create Date: 2024-09-19 16:19:48.824926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d2b9fe59d5a'
down_revision: Union[str, None] = 'ce3b5d19e70a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_material', sa.Column('section_id', sa.UUID(), nullable=True))
    op.drop_index('ix_course_material_course_id', table_name='course_material')
    op.create_index(op.f('ix_course_material_section_id'), 'course_material', ['section_id'], unique=False)
    op.drop_constraint('course_material_course_id_fkey', 'course_material', type_='foreignkey')
    op.create_foreign_key(None, 'course_material', 'section', ['section_id'], ['section_id'])
    op.drop_column('course_material', 'course_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_material', sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'course_material', type_='foreignkey')
    op.create_foreign_key('course_material_course_id_fkey', 'course_material', 'course', ['course_id'], ['course_id'])
    op.drop_index(op.f('ix_course_material_section_id'), table_name='course_material')
    op.create_index('ix_course_material_course_id', 'course_material', ['course_id'], unique=False)
    op.drop_column('course_material', 'section_id')
    # ### end Alembic commands ###
