"""Adding image path to student

Revision ID: 1ad6319b9ef9
Revises: c78d685fc3e7
Create Date: 2024-10-10 19:21:42.571791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad6319b9ef9'
down_revision: Union[str, None] = 'c78d685fc3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_student_image_path'), 'student', ['image_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_image_path'), table_name='student')
    # ### end Alembic commands ###
