"""Alter payment confirmed

Revision ID: 28be44d4e8de
Revises: e29efd9a64f1
Create Date: 2024-10-17 18:27:15.360188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28be44d4e8de'
down_revision: Union[str, None] = 'e29efd9a64f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
