"""On delete on courseId

Revision ID: 45c03edcdfd6
Revises: fd3f026bf5ca
Create Date: 2024-10-05 12:04:33.650671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c03edcdfd6'
down_revision: Union[str, None] = 'fd3f026bf5ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_s_admin_email', table_name='admin_s')
    op.drop_index('ix_admin_s_admin_id', table_name='admin_s')
    op.drop_index('ix_admin_s_admin_name', table_name='admin_s')
    op.drop_index('ix_admin_s_admin_nic', table_name='admin_s')
    op.drop_index('ix_admin_s_admin_password', table_name='admin_s')
    op.drop_index('ix_admin_s_admin_phone', table_name='admin_s')
    op.drop_table('admin_s')
    op.drop_constraint('section_course_id_fkey', 'section', type_='foreignkey')
    op.create_foreign_key(None, 'section', 'course', ['course_id'], ['course_id'], ondelete='CASCADE')
    op.drop_index('ix_student_image_path', table_name='student')
    op.drop_column('student', 'image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_student_image_path', 'student', ['image_path'], unique=False)
    op.drop_constraint(None, 'section', type_='foreignkey')
    op.create_foreign_key('section_course_id_fkey', 'section', 'course', ['course_id'], ['course_id'])
    op.create_table('admin_s',
    sa.Column('admin_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('admin_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin_nic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('admin_id', name='admin_s_pkey')
    )
    op.create_index('ix_admin_s_admin_phone', 'admin_s', ['admin_phone'], unique=False)
    op.create_index('ix_admin_s_admin_password', 'admin_s', ['admin_password'], unique=False)
    op.create_index('ix_admin_s_admin_nic', 'admin_s', ['admin_nic'], unique=False)
    op.create_index('ix_admin_s_admin_name', 'admin_s', ['admin_name'], unique=False)
    op.create_index('ix_admin_s_admin_id', 'admin_s', ['admin_id'], unique=False)
    op.create_index('ix_admin_s_admin_email', 'admin_s', ['admin_email'], unique=False)
    # ### end Alembic commands ###
