"""Alter payment confirmed 2

Revision ID: 58ab4ca4a26b
Revises: 28be44d4e8de
Create Date: 2024-10-17 18:30:42.240070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ab4ca4a26b'
down_revision: Union[str, None] = '28be44d4e8de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_payment_confirmed'), 'payment', ['confirmed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_confirmed'), table_name='payment')
    op.drop_column('payment', 'confirmed')
    # ### end Alembic commands ###
