"""lecturer change2

Revision ID: 75afc0843152
Revises: f5ce4b4a9db7
Create Date: 2024-09-23 18:04:55.271082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75afc0843152'
down_revision: Union[str, None] = 'f5ce4b4a9db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('semester_id', sa.UUID(), nullable=True))
    op.add_column('student', sa.Column('newStudent_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_student_newStudent_id'), 'student', ['newStudent_id'], unique=False)
    op.create_index(op.f('ix_student_semester_id'), 'student', ['semester_id'], unique=False)
    op.create_foreign_key(None, 'student', 'semester', ['semester_id'], ['semester_id'])
    op.create_foreign_key(None, 'student', 'new_student', ['newStudent_id'], ['newStudent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_index(op.f('ix_student_semester_id'), table_name='student')
    op.drop_index(op.f('ix_student_newStudent_id'), table_name='student')
    op.drop_column('student', 'newStudent_id')
    op.drop_column('student', 'semester_id')
    # ### end Alembic commands ###
