"""Change the new student table

Revision ID: 783854647fc7
Revises: 8e3d7b386a82
Create Date: 2024-10-15 22:22:48.129628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783854647fc7'
down_revision: Union[str, None] = '8e3d7b386a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_student', sa.Column('payment_path', sa.String(), nullable=True))
    op.drop_index('ix_new_student_gender', table_name='new_student')
    op.drop_index('ix_new_student_payment_id', table_name='new_student')
    op.create_index(op.f('ix_new_student_payment_path'), 'new_student', ['payment_path'], unique=False)
    op.drop_constraint('new_student_payment_id_fkey', 'new_student', type_='foreignkey')
    op.drop_column('new_student', 'gender')
    op.drop_column('new_student', 'payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_student', sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('new_student', sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('new_student_payment_id_fkey', 'new_student', 'payment', ['payment_id'], ['payment_id'])
    op.drop_index(op.f('ix_new_student_payment_path'), table_name='new_student')
    op.create_index('ix_new_student_payment_id', 'new_student', ['payment_id'], unique=False)
    op.create_index('ix_new_student_gender', 'new_student', ['gender'], unique=False)
    op.drop_column('new_student', 'payment_path')
    # ### end Alembic commands ###
