"""altered student

Revision ID: 88359190a390
Revises: 00f30cc14aaf
Create Date: 2024-09-28 01:01:17.566847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88359190a390'
down_revision: Union[str, None] = '00f30cc14aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('image_path', sa.String(), nullable=True))
    op.create_index(op.f('ix_student_image_path'), 'student', ['image_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_image_path'), table_name='student')
    op.drop_column('student', 'image_path')
    # ### end Alembic commands ###
