"""Removing fk from courses and semesters

Revision ID: 8e3d7b386a82
Revises: 9de24dde2d43
Create Date: 2024-10-14 19:40:05.103090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3d7b386a82'
down_revision: Union[str, None] = '9de24dde2d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_course_semester_id', table_name='course')
    op.drop_constraint('course_semester_id_fkey', 'course', type_='foreignkey')
    op.drop_column('course', 'semester_id')
    op.create_index(op.f('ix_quiz_attempts'), 'quiz', ['attempts'], unique=False)
    op.create_index(op.f('ix_quiz_is_enabled'), 'quiz', ['is_enabled'], unique=False)
    op.drop_index('ix_semester_program_id', table_name='semester')
    op.drop_constraint('semester_program_id_fkey', 'semester', type_='foreignkey')
    op.drop_column('semester', 'program_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semester', sa.Column('program_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('semester_program_id_fkey', 'semester', 'program', ['program_id'], ['program_id'])
    op.create_index('ix_semester_program_id', 'semester', ['program_id'], unique=False)
    op.drop_index(op.f('ix_quiz_is_enabled'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_attempts'), table_name='quiz')
    op.add_column('course', sa.Column('semester_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('course_semester_id_fkey', 'course', 'semester', ['semester_id'], ['semester_id'])
    op.create_index('ix_course_semester_id', 'course', ['semester_id'], unique=False)
    # ### end Alembic commands ###
