"""clear

Revision ID: 96a0be656bcd
Revises: 
Create Date: 2024-09-11 21:47:29.933892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96a0be656bcd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lecturer_lecturer_email', table_name='lecturer')
    op.drop_index('ix_lecturer_lecturer_id', table_name='lecturer')
    op.drop_index('ix_lecturer_lecturer_name', table_name='lecturer')
    op.drop_index('ix_lecturer_lecturer_nic', table_name='lecturer')
    op.drop_index('ix_lecturer_lecturer_password', table_name='lecturer')
    op.drop_index('ix_lecturer_lecturer_phone', table_name='lecturer')
    op.drop_table('lecturer')
    op.drop_index('ix_new_student_OL_path', table_name='new_student')
    op.drop_index('ix_new_student_address', table_name='new_student')
    op.drop_index('ix_new_student_date', table_name='new_student')
    op.drop_index('ix_new_student_email', table_name='new_student')
    op.drop_index('ix_new_student_gender', table_name='new_student')
    op.drop_index('ix_new_student_name', table_name='new_student')
    op.drop_index('ix_new_student_newStudent_id', table_name='new_student')
    op.drop_index('ix_new_student_payment_id', table_name='new_student')
    op.drop_index('ix_new_student_program_id', table_name='new_student')
    op.drop_table('new_student')
    op.drop_index('ix_student_date', table_name='student')
    op.drop_index('ix_student_newStudent_id', table_name='student')
    op.drop_index('ix_student_password', table_name='student')
    op.drop_index('ix_student_student_id', table_name='student')
    op.drop_table('student')
    op.drop_index('ix_course_semester_program_course_id', table_name='course_semester_program')
    op.drop_index('ix_course_semester_program_program_id', table_name='course_semester_program')
    op.drop_index('ix_course_semester_program_semester_id', table_name='course_semester_program')
    op.drop_table('course_semester_program')
    op.drop_index('ix_admin_admin_email', table_name='admin')
    op.drop_index('ix_admin_admin_id', table_name='admin')
    op.drop_index('ix_admin_admin_name', table_name='admin')
    op.drop_index('ix_admin_admin_nic', table_name='admin')
    op.drop_index('ix_admin_admin_password', table_name='admin')
    op.drop_index('ix_admin_admin_phone', table_name='admin')
    op.drop_table('admin')
    op.drop_index('ix_ lecturer_assigned_for_course_id', table_name=' lecturer_assigned_for')
    op.drop_index('ix_ lecturer_assigned_for_lecturer_id', table_name=' lecturer_assigned_for')
    op.drop_index('ix_ lecturer_assigned_for_program_id', table_name=' lecturer_assigned_for')
    op.drop_index('ix_ lecturer_assigned_for_semester_id', table_name=' lecturer_assigned_for')
    op.drop_table(' lecturer_assigned_for')
    op.drop_index('ix_semester_semester', table_name='semester')
    op.drop_index('ix_semester_semester_id', table_name='semester')
    op.drop_index('ix_semester_status', table_name='semester')
    op.drop_index('ix_semester_year', table_name='semester')
    op.drop_table('semester')
    op.drop_index('ix_course_course_description', table_name='course')
    op.drop_index('ix_course_course_id', table_name='course')
    op.drop_index('ix_course_course_name', table_name='course')
    op.drop_index('ix_course_enrollment_key', table_name='course')
    op.drop_table('course')
    op.drop_index('ix_payment_amount', table_name='payment')
    op.drop_index('ix_payment_bank', table_name='payment')
    op.drop_index('ix_payment_branch', table_name='payment')
    op.drop_index('ix_payment_date', table_name='payment')
    op.drop_index('ix_payment_payment_id', table_name='payment')
    op.drop_index('ix_payment_receipt_path', table_name='payment')
    op.drop_index('ix_payment_status', table_name='payment')
    op.drop_index('ix_payment_student_number', table_name='payment')
    op.drop_index('ix_payment_type', table_name='payment')
    op.drop_table('payment')
    op.drop_index('ix_program_duration', table_name='program')
    op.drop_index('ix_program_program_id', table_name='program')
    op.drop_index('ix_program_program_name', table_name='program')
    op.drop_table('program')
    op.drop_index('ix_affiliated_university_affiliated_with', table_name='affiliated_university')
    op.drop_index('ix_affiliated_university_program_id', table_name='affiliated_university')
    op.drop_table('affiliated_university')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliated_university',
    sa.Column('affiliated_with', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('program_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program.program_id'], name='affiliated_university_program_id_fkey'),
    sa.PrimaryKeyConstraint('affiliated_with', 'program_id', name='affiliated_university_pkey')
    )
    op.create_index('ix_affiliated_university_program_id', 'affiliated_university', ['program_id'], unique=False)
    op.create_index('ix_affiliated_university_affiliated_with', 'affiliated_university', ['affiliated_with'], unique=False)
    op.create_table('program',
    sa.Column('program_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('program_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('program_id', name='program_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_program_program_name', 'program', ['program_name'], unique=False)
    op.create_index('ix_program_program_id', 'program', ['program_id'], unique=False)
    op.create_index('ix_program_duration', 'program', ['duration'], unique=False)
    op.create_table('payment',
    sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bank', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('receipt_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('student_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_number'], ['student.student_id'], name='payment_student_number_fkey'),
    sa.PrimaryKeyConstraint('payment_id', name='payment_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_payment_type', 'payment', ['type'], unique=False)
    op.create_index('ix_payment_student_number', 'payment', ['student_number'], unique=False)
    op.create_index('ix_payment_status', 'payment', ['status'], unique=False)
    op.create_index('ix_payment_receipt_path', 'payment', ['receipt_path'], unique=False)
    op.create_index('ix_payment_payment_id', 'payment', ['payment_id'], unique=False)
    op.create_index('ix_payment_date', 'payment', ['date'], unique=False)
    op.create_index('ix_payment_branch', 'payment', ['branch'], unique=False)
    op.create_index('ix_payment_bank', 'payment', ['bank'], unique=False)
    op.create_index('ix_payment_amount', 'payment', ['amount'], unique=False)
    op.create_table('course',
    sa.Column('course_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('course_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('enrollment_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('course_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('course_id', name='course_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_course_enrollment_key', 'course', ['enrollment_key'], unique=False)
    op.create_index('ix_course_course_name', 'course', ['course_name'], unique=False)
    op.create_index('ix_course_course_id', 'course', ['course_id'], unique=False)
    op.create_index('ix_course_course_description', 'course', ['course_description'], unique=False)
    op.create_table('semester',
    sa.Column('semester_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('semester', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('semester_id', name='semester_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_semester_year', 'semester', ['year'], unique=False)
    op.create_index('ix_semester_status', 'semester', ['status'], unique=False)
    op.create_index('ix_semester_semester_id', 'semester', ['semester_id'], unique=False)
    op.create_index('ix_semester_semester', 'semester', ['semester'], unique=False)
    op.create_table(' lecturer_assigned_for',
    sa.Column('course_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('semester_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('program_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lecturer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], name=' lecturer_assigned_for_course_id_fkey'),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturer.lecturer_id'], name=' lecturer_assigned_for_lecturer_id_fkey'),
    sa.ForeignKeyConstraint(['program_id'], ['program.program_id'], name=' lecturer_assigned_for_program_id_fkey'),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.semester_id'], name=' lecturer_assigned_for_semester_id_fkey'),
    sa.PrimaryKeyConstraint('course_id', 'semester_id', 'program_id', 'lecturer_id', name=' lecturer_assigned_for_pkey')
    )
    op.create_index('ix_ lecturer_assigned_for_semester_id', ' lecturer_assigned_for', ['semester_id'], unique=False)
    op.create_index('ix_ lecturer_assigned_for_program_id', ' lecturer_assigned_for', ['program_id'], unique=False)
    op.create_index('ix_ lecturer_assigned_for_lecturer_id', ' lecturer_assigned_for', ['lecturer_id'], unique=False)
    op.create_index('ix_ lecturer_assigned_for_course_id', ' lecturer_assigned_for', ['course_id'], unique=False)
    op.create_table('admin',
    sa.Column('admin_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('admin_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin_nic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('admin_id', name='admin_pkey')
    )
    op.create_index('ix_admin_admin_phone', 'admin', ['admin_phone'], unique=False)
    op.create_index('ix_admin_admin_password', 'admin', ['admin_password'], unique=False)
    op.create_index('ix_admin_admin_nic', 'admin', ['admin_nic'], unique=False)
    op.create_index('ix_admin_admin_name', 'admin', ['admin_name'], unique=False)
    op.create_index('ix_admin_admin_id', 'admin', ['admin_id'], unique=False)
    op.create_index('ix_admin_admin_email', 'admin', ['admin_email'], unique=False)
    op.create_table('course_semester_program',
    sa.Column('program_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('semester_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], name='course_semester_program_course_id_fkey'),
    sa.ForeignKeyConstraint(['program_id'], ['program.program_id'], name='course_semester_program_program_id_fkey'),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.semester_id'], name='course_semester_program_semester_id_fkey'),
    sa.PrimaryKeyConstraint('program_id', 'course_id', 'semester_id', name='course_semester_program_pkey')
    )
    op.create_index('ix_course_semester_program_semester_id', 'course_semester_program', ['semester_id'], unique=False)
    op.create_index('ix_course_semester_program_program_id', 'course_semester_program', ['program_id'], unique=False)
    op.create_index('ix_course_semester_program_course_id', 'course_semester_program', ['course_id'], unique=False)
    op.create_table('student',
    sa.Column('student_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('newStudent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['newStudent_id'], ['new_student.newStudent_id'], name='student_newStudent_id_fkey'),
    sa.PrimaryKeyConstraint('student_id', name='student_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_student_student_id', 'student', ['student_id'], unique=False)
    op.create_index('ix_student_password', 'student', ['password'], unique=False)
    op.create_index('ix_student_newStudent_id', 'student', ['newStudent_id'], unique=False)
    op.create_index('ix_student_date', 'student', ['date'], unique=False)
    op.create_table('new_student',
    sa.Column('newStudent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('OL_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('AL_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('program_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.payment_id'], name='new_student_payment_id_fkey'),
    sa.ForeignKeyConstraint(['program_id'], ['program.program_id'], name='new_student_program_id_fkey'),
    sa.PrimaryKeyConstraint('newStudent_id', name='new_student_pkey')
    )
    op.create_index('ix_new_student_program_id', 'new_student', ['program_id'], unique=False)
    op.create_index('ix_new_student_payment_id', 'new_student', ['payment_id'], unique=False)
    op.create_index('ix_new_student_newStudent_id', 'new_student', ['newStudent_id'], unique=False)
    op.create_index('ix_new_student_name', 'new_student', ['name'], unique=False)
    op.create_index('ix_new_student_gender', 'new_student', ['gender'], unique=False)
    op.create_index('ix_new_student_email', 'new_student', ['email'], unique=False)
    op.create_index('ix_new_student_date', 'new_student', ['date'], unique=False)
    op.create_index('ix_new_student_address', 'new_student', ['address'], unique=False)
    op.create_index('ix_new_student_OL_path', 'new_student', ['OL_path'], unique=False)
    op.create_table('lecturer',
    sa.Column('lecturer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lecturer_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lecturer_nic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lecturer_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lecturer_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lecturer_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('lecturer_id', name='lecturer_pkey')
    )
    op.create_index('ix_lecturer_lecturer_phone', 'lecturer', ['lecturer_phone'], unique=False)
    op.create_index('ix_lecturer_lecturer_password', 'lecturer', ['lecturer_password'], unique=False)
    op.create_index('ix_lecturer_lecturer_nic', 'lecturer', ['lecturer_nic'], unique=False)
    op.create_index('ix_lecturer_lecturer_name', 'lecturer', ['lecturer_name'], unique=False)
    op.create_index('ix_lecturer_lecturer_id', 'lecturer', ['lecturer_id'], unique=False)
    op.create_index('ix_lecturer_lecturer_email', 'lecturer', ['lecturer_email'], unique=False)
    # ### end Alembic commands ###
