"""altered student table

Revision ID: 96c2919d38fd
Revises: 
Create Date: 2024-09-12 18:25:55.549503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c2919d38fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('email', sa.String(), nullable=True))
    op.drop_index('ix_student_date', table_name='student')
    op.create_index(op.f('ix_student_email'), 'student', ['email'], unique=False)
    op.drop_column('student', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_student_email'), table_name='student')
    op.create_index('ix_student_date', 'student', ['date'], unique=False)
    op.drop_column('student', 'email')
    # ### end Alembic commands ###
