"""Adding foreign keys for courses and semesters

Revision ID: 98f7ea3f8913
Revises: 1ad6319b9ef9
Create Date: 2024-10-11 21:52:51.991943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f7ea3f8913'
down_revision: Union[str, None] = '1ad6319b9ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('semester_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_course_semester_id'), 'course', ['semester_id'], unique=False)
    op.create_foreign_key(None, 'course', 'semester', ['semester_id'], ['semester_id'])
    op.add_column('semester', sa.Column('program_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_semester_program_id'), 'semester', ['program_id'], unique=False)
    op.create_foreign_key(None, 'semester', 'program', ['program_id'], ['program_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'semester', type_='foreignkey')
    op.drop_index(op.f('ix_semester_program_id'), table_name='semester')
    op.drop_column('semester', 'program_id')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_index(op.f('ix_course_semester_id'), table_name='course')
    op.drop_column('course', 'semester_id')
    # ### end Alembic commands ###
