"""removed newStudent ID

Revision ID: 9bd528cc57f9
Revises: 96c2919d38fd
Create Date: 2024-09-12 18:45:21.456822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bd528cc57f9'
down_revision: Union[str, None] = '96c2919d38fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_newStudent_id', table_name='student')
    op.drop_constraint('student_newStudent_id_fkey', 'student', type_='foreignkey')
    op.drop_column('student', 'newStudent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('newStudent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('student_newStudent_id_fkey', 'student', 'new_student', ['newStudent_id'], ['newStudent_id'])
    op.create_index('ix_student_newStudent_id', 'student', ['newStudent_id'], unique=False)
    # ### end Alembic commands ###
