"""Adding image path to admin

Revision ID: b6ac49a316df
Revises: ac66be328413
Create Date: 2024-10-16 18:22:58.363248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ac49a316df'
down_revision: Union[str, None] = 'ac66be328413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('image_path', sa.String(), nullable=True))
    op.create_index(op.f('ix_admin_image_path'), 'admin', ['image_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_image_path'), table_name='admin')
    op.drop_column('admin', 'image_path')
    # ### end Alembic commands ###
