"""Adding image to courses

Revision ID: c455de038910
Revises: abb23bb71618
Create Date: 2024-10-05 15:40:54.734625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c455de038910'
down_revision: Union[str, None] = 'abb23bb71618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('course_image', sa.String(), nullable=True))
    op.create_index(op.f('ix_course_course_image'), 'course', ['course_image'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_course_image'), table_name='course')
    op.drop_column('course', 'course_image')
    # ### end Alembic commands ###
