"""Adding fields to programs

Revision ID: c78d685fc3e7
Revises: c455de038910
Create Date: 2024-10-07 09:16:56.170042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c78d685fc3e7'
down_revision: Union[str, None] = 'c455de038910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program', sa.Column('program_description', sa.String(), nullable=True))
    op.add_column('program', sa.Column('university_name', sa.String(), nullable=True))
    op.add_column('program', sa.Column('university_image', sa.String(), nullable=True))
    op.create_index(op.f('ix_program_program_description'), 'program', ['program_description'], unique=False)
    op.create_index(op.f('ix_program_university_image'), 'program', ['university_image'], unique=False)
    op.create_index(op.f('ix_program_university_name'), 'program', ['university_name'], unique=False)
    op.drop_column('student', 'image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_program_university_name'), table_name='program')
    op.drop_index(op.f('ix_program_university_image'), table_name='program')
    op.drop_index(op.f('ix_program_program_description'), table_name='program')
    op.drop_column('program', 'university_image')
    op.drop_column('program', 'university_name')
    op.drop_column('program', 'program_description')
    # ### end Alembic commands ###
