"""Alter new students

Revision ID: ceb4ef14860f
Revises: 94d67be8ab72
Create Date: 2024-10-17 16:26:48.870892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb4ef14860f'
down_revision: Union[str, None] = '94d67be8ab72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_student', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_new_student_confirmed'), 'new_student', ['confirmed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_new_student_confirmed'), table_name='new_student')
    op.drop_column('new_student', 'confirmed')
    # ### end Alembic commands ###
