"""lecturer change

Revision ID: f5ce4b4a9db7
Revises: e2f8f056dfb0
Create Date: 2024-09-23 18:00:49.181278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5ce4b4a9db7'
down_revision: Union[str, None] = 'e2f8f056dfb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_enrolled_courses_course_id', table_name='student_enrolled_courses')
    op.drop_index('ix_student_enrolled_courses_semester_id', table_name='student_enrolled_courses')
    op.drop_index('ix_student_enrolled_courses_student_id', table_name='student_enrolled_courses')
    op.drop_table('student_enrolled_courses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_enrolled_courses',
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('semester_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], name='student_enrolled_courses_course_id_fkey'),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.semester_id'], name='student_enrolled_courses_semester_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], name='student_enrolled_courses_student_id_fkey'),
    sa.PrimaryKeyConstraint('course_id', 'student_id', 'semester_id', name='student_enrolled_courses_pkey')
    )
    op.create_index('ix_student_enrolled_courses_student_id', 'student_enrolled_courses', ['student_id'], unique=False)
    op.create_index('ix_student_enrolled_courses_semester_id', 'student_enrolled_courses', ['semester_id'], unique=False)
    op.create_index('ix_student_enrolled_courses_course_id', 'student_enrolled_courses', ['course_id'], unique=False)
    # ### end Alembic commands ###
