"""change student course

Revision ID: fd3f026bf5ca
Revises: 75afc0843152
Create Date: 2024-09-23 18:12:47.462507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd3f026bf5ca'
down_revision: Union[str, None] = '75afc0843152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_enrolled_courses',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('semester_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.semester_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('course_id', 'student_id', 'semester_id')
    )
    op.create_index(op.f('ix_student_enrolled_courses_course_id'), 'student_enrolled_courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_student_enrolled_courses_semester_id'), 'student_enrolled_courses', ['semester_id'], unique=False)
    op.create_index(op.f('ix_student_enrolled_courses_student_id'), 'student_enrolled_courses', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_enrolled_courses_student_id'), table_name='student_enrolled_courses')
    op.drop_index(op.f('ix_student_enrolled_courses_semester_id'), table_name='student_enrolled_courses')
    op.drop_index(op.f('ix_student_enrolled_courses_course_id'), table_name='student_enrolled_courses')
    op.drop_table('student_enrolled_courses')
    # ### end Alembic commands ###
